namenode:
  image: uhopper/hadoop-namenode
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - tekreliance:/hadoop/dfs/name
  environment:
    - GANGLIA_HOST=fnug
    - CLUSTER_NAME=tekreliance
